# Generated by Django 4.2 on 2025-03-07 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_Producto', models.CharField(max_length=100)),
                ('tipo_Producto', models.CharField(choices=[('1', 'Vino'), ('2', 'Ron'), ('3', 'Cerveza'), ('4', 'vodka'), ('5', 'Ginebra'), ('6', 'Tequila'), ('7', 'Guaro'), ('8', 'smirnoff'), ('9', 'Four Loko')], max_length=1)),
                ('medidas', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(max_length=200)),
                ('cantidad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('tipoUsuario', models.CharField(choices=[('1', 'Administrador'), ('2', 'Cliente'), ('3', 'Proveedor')], default=2, max_length=1)),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('N', 'No binario')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(max_length=100)),
                ('correo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='licorera_los_J.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_de_producto', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descripcion', models.TextField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='licorera_los_J.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='licorera_los_J.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pedido', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_factura', models.DateField(help_text='AAAA-MM-DD')),
                ('hora_factura', models.TimeField(help_text='HH:MM')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='licorera_los_J.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='licorera_los_J.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='licorera_los_J.producto')),
            ],
        ),
    ]
