# Generated by Django 4.2 on 2025-03-23 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='correo',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
