# Generated by Django 4.2 on 2025-03-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0002_remove_usuarios_correo_usuarios_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True),
        ),
    ]
