# Generated by Django 4.2 on 2025-03-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0003_alter_usuarios_contrasena_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='direccion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
