# Generated by Django 4.2 on 2025-03-25 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0004_alter_usuarios_contrasena_alter_usuarios_direccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateTimeField(blank=True, default='', null=True),
        ),
    ]
