# Generated by Django 4.2 on 2025-04-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0006_alter_usuarios_fecha_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='producto/'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuario/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='AAAA-MM-DD', null=True),
        ),
    ]
