# Generated by Django 4.2.20 on 2025-04-03 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0007_productos_foto_usuarios_foto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='foto',
            field=models.ImageField(blank=True, default='producto/default.svg', null=True, upload_to='producto/'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='foto',
            field=models.ImageField(blank=True, default='usuario/default.svg', null=True, upload_to='usuario/'),
        ),
    ]
