# Generated by Django 4.2 on 2025-05-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0012_usuarios_carrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesfacturas',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detallesfacturas',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
