# Generated by Django 4.2 on 2025-05-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0013_detallesfacturas_cantidad_detallesfacturas_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesfacturas',
            name='hora_compra',
            field=models.TimeField(blank=True, help_text='HH:MM', null=True),
        ),
        migrations.AlterField(
            model_name='detallesfacturas',
            name='subtotal',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='valor_pedido',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='facturas',
            name='valor_total',
            field=models.IntegerField(),
        ),
    ]
