# Generated by Django 4.2 on 2025-05-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licorera_los_J', '0013_detallesfacturas_cantidad_detallesfacturas_subtotal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='carrito',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
